### PR TITLE
Replace Wikipedia links in Google search results with their mobile version

### PR DESCRIPTION
**Pull request by maxloh**
Match pattern created from list of Google domains (https://www.google.com/supported_domains)

### CODE REVIEW

**Comment by jathu** [comment]
Hey thanks for the PR, can you give a bit more detail on why this is required?

**Comment by maxloh** [comment]
My computer is not fast. After clicking search results in Google, it takes about 1 second for redirecting the page to Wikipedia mobile site.

It would be faster if we replace search results URL with mobile version instead of redirecting after user clicked on them.

**Comment by maxloh** [comment]
My computer is not fast. After clicking search results in Google, it takes about 1 second for redirecting the page to Wikipedia mobile site.

It would be faster if we replace search results URL with mobile version instead of redirecting after user clicked on them.

**Comment by jathu** [comment]
Sorry, I'm hesitant to directly replace links within the dom itself. I intended this extension to be very minimal, and this PR seems out of scope of that goal. Please feel free to fork the repo :)

**Pull request closed without merging**
